repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
      - id: poetry-check
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: poetry run ruff . --fix
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: poetry run pytest tests/
        language: system
        types: [python]
