version = 0.1
[deepa.deploy.parameters]
stack_name = "python-lambda-template-app"
resolve_s3 = true
s3_prefix = "python-lambda-template-app"
region = "eu-west-3"
profile = "deepia"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.deploy.parameters]
stack_name = "demo-ci-cd"
resolve_s3 = true
s3_prefix = "demo-ci-cd"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
