name: CI
run-name: Autoformat, Lint, Test
on: [push]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Poetry Env
        id: poetry-env
        run: poetry install --with dev
      - name: Lint with ruff
        id: ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 ./python_lambda_template
          poetry run ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 ./tests
          # default set of ruff rules with GitHub Annotations
          poetry run ruff --format=github --target-version=py310 ./python_lambda_template
          poetry run ruff --format=github --target-version=py310 ./tests
      - name: Black
        id: black
        run: poetry run black --check ./python_lambda_template
      - name: ISort
        id: isort
        run: poetry run isort ./python_lambda_template --check-only
      - name: Pytest
        id: pytest
        run: poetry run pytest tests/
